package biodata01;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Date;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author WINDOWS 11
 */
public class biodataKuis2_01 extends javax.swing.JFrame {

    /**
     * Creates new form biodataKuis2_01
     */
    public biodataKuis2_01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupJk = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        namaText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TelpText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pendidikanComboBox = new javax.swing.JComboBox<>();
        perempuanRadioButton = new javax.swing.JRadioButton();
        lakiRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        fotografiCheckBox = new javax.swing.JCheckBox();
        menulisCheckBox = new javax.swing.JCheckBox();
        membacaCheckBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        DaftarButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        IPKjFormatted = new javax.swing.JFormattedTextField();
        nikText1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        ftftgllahir = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM PENDAFTARAN ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1)
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 50));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Alamat");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 50, -1));

        namaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextActionPerformed(evt);
            }
        });
        jPanel1.add(namaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 280, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(":");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 10, -1));

        TelpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelpTextActionPerformed(evt);
            }
        });
        TelpText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelpTextKeyTyped(evt);
            }
        });
        jPanel1.add(TelpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 160, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Nama");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 50, -1));

        pendidikanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D1", "D2", "D3", "D4 / S1", "S2", "S3" }));
        pendidikanComboBox.setSelectedIndex(-1);
        pendidikanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendidikanComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(pendidikanComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 100, -1));

        btnGroupJk.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(perempuanRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        btnGroupJk.add(lakiRadioButton);
        lakiRadioButton.setText("Laki-laki");
        lakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(lakiRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Jenis Kelamin");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        fotografiCheckBox.setText("Fotografi");
        fotografiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotografiCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(fotografiCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        menulisCheckBox.setText("Menulis");
        jPanel1.add(menulisCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        membacaCheckBox.setText("Membaca");
        jPanel1.add(membacaCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Hobi");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 50, -1));

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        jScrollPane1.setViewportView(alamatTextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 280, -1));

        DaftarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DaftarButton.setText("Daftar");
        DaftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DaftarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("NIK");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(":");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 10, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(":");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 10, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(":");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 10, -1));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("IPK");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 70, -1));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(":");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 10, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Telp");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText(":");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 10, -1));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Pendidikan");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 70, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText(":");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 10, -1));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(":");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 10, -1));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(":");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 10, -1));

        IPKjFormatted.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                IPKjFormattedFocusLost(evt);
            }
        });
        IPKjFormatted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPKjFormattedActionPerformed(evt);
            }
        });
        jPanel1.add(IPKjFormatted, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 100, -1));

        nikText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikText1ActionPerformed(evt);
            }
        });
        jPanel1.add(nikText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, -1));

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Tanggal Lahir");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 80, -1));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText(":");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 10, -1));

        ftftgllahir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        ftftgllahir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftftgllahirFocusLost(evt);
            }
        });
        ftftgllahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftftgllahirActionPerformed(evt);
            }
        });
        jPanel1.add(ftftgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 220, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextActionPerformed

    private void TelpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelpTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelpTextActionPerformed

    private void pendidikanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendidikanComboBoxActionPerformed
        // TODO add your handling code here:
        String pendidikan = (String) pendidikanComboBox.getSelectedItem();

    // Periksa apakah pilihan adalah SD, SMP, atau SMA
    if (pendidikan.equals("SD") || pendidikan.equals("SMP") || pendidikan.equals("SMA")) {
        // Jika SD, SMP, atau SMA dipilih, tampilkan pesan tidak bisa mendaftar
        JOptionPane.showMessageDialog(this, "Pendidikan SD, SMP, dan SMA tidak bisa mendaftar.", 
                "Pendaftaran Gagal", JOptionPane.ERROR_MESSAGE);
    } 
//      else if (pendidikan.equals("D1") || pendidikan.equals("D2") || pendidikan.equals("D3") || pendidikan.equals("S1") || pendidikan.equals("S2") || pendidikan.equals("S3")) {
//        // Jika D1, D2, D3, S1, S2, atau S3 dipilih, lanjutkan pendaftaran
//        JOptionPane.showMessageDialog(this, "Selamat, Anda bisa melanjutkan pendaftaran.", 
//                "Pendaftaran Berhasil", JOptionPane.INFORMATION_MESSAGE);
//    }
    }//GEN-LAST:event_pendidikanComboBoxActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
        perempuanRadioButton.setActionCommand("Perempuan");
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed

    private void lakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRadioButtonActionPerformed
        // TODO add your handling code here:
        lakiRadioButton.setActionCommand("Laki-laki");
    }//GEN-LAST:event_lakiRadioButtonActionPerformed

    private void fotografiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotografiCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fotografiCheckBoxActionPerformed

    private void DaftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarButtonActionPerformed
                                              
    // Validasi inputan form
    if (nikText1.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "NIK harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (namaText.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Nama harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (alamatTextArea.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Alamat harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    Object pendidikanItem = pendidikanComboBox.getSelectedItem();
    if (pendidikanItem == null || pendidikanItem.toString().equals("-")) {
        JOptionPane.showMessageDialog(this, "Jurusan harus dipilih!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    ButtonModel genderModel = btnGroupJk.getSelection();
    if (genderModel == null) {
        JOptionPane.showMessageDialog(this, "Gender harus dipilih!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Validasi IPK
    String ipkString = IPKjFormatted.getText().trim();
    if (ipkString.isEmpty()) {
        JOptionPane.showMessageDialog(this, "IPK harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    try {
        double ipk = Double.parseDouble(ipkString);
        if (ipk < 3.01 || ipk > 4.00) {
            JOptionPane.showMessageDialog(this, "IPK harus antara 3.01 dan 4.00", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "IPK tidak valid. Masukkan angka yang benar.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Menampilkan pesan pendaftaran berhasil
    JOptionPane.showMessageDialog(this, "Anda berhasil mendaftar", "Pendaftaran Berhasil", JOptionPane.INFORMATION_MESSAGE);
    
    // Reset form setelah pendaftaran berhasil
    
    nikText1.setText(""); 
    namaText.setText(""); 
    alamatTextArea.setText(""); 
    btnGroupJk.clearSelection();
    TelpText.setText(""); 
    menulisCheckBox.setSelected(false);
    membacaCheckBox.setSelected(false);
    fotografiCheckBox.setSelected(false);
    ftftgllahir.setText(""); 
    pendidikanComboBox.setSelectedIndex(-1); 
    IPKjFormatted.setText("");
    
//    resetForm();
}

private void resetForm() {
    // Kosongkan semua field di form
    nikText1.setText("");  // Kosongkan NIK
    namaText.setText("");  // Kosongkan Nama
    alamatTextArea.setText("");  // Kosongkan Alamat
    pendidikanComboBox.setSelectedIndex(-1);  // Reset combo box ke nilai default
    btnGroupJk.clearSelection();  // Reset pilihan radio button (Gender)
    lakiRadioButton.setSelected(false);
    perempuanRadioButton.setSelected(false);
    membacaCheckBox.setSelected(false);  // Kosongkan Checkbox Hobi Membaca
    fotografiCheckBox.setSelected(false);  // Kosongkan Checkbox Hobi Fotografi
    menulisCheckBox.setSelected(false);  // Kosongkan Checkbox Hobi Menulis
    IPKjFormatted.setText("");  // Kosongkan IPK field
    TelpText.setText("");  // Kosongkan input Telp
    ftftgllahir.setText("");  // Kosongkan input Tanggal Lahir
    }//GEN-LAST:event_DaftarButtonActionPerformed

    private void nikText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikText1ActionPerformed

    private void TelpTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelpTextKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
    // Cek apakah karakter yang dimasukkan bukan angka
    if (!Character.isDigit(c)) {
        evt.consume(); // Abaikan karakter jika bukan angka
    }
    }//GEN-LAST:event_TelpTextKeyTyped

    private void IPKjFormattedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPKjFormattedActionPerformed
        // TODO add your handling code here:
       String ipkString = IPKjFormatted.getText().trim();

    try {
        if (!ipkString.isEmpty()) {
            double ipk = Double.parseDouble(ipkString);

            if (ipk >= 0.00 && ipk <= 4.00) {
                System.out.println("IPK valid: " + ipk);
            } else {
                JOptionPane.showMessageDialog(this, "IPK tidak valid. Harus antara 0.00 dan 4.00.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                IPKjFormatted.setText("");
            }
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "IPK tidak valid. Masukkan angka dengan format yang benar.",
                "Error", JOptionPane.ERROR_MESSAGE);
        IPKjFormatted.setText("");
    }
    }//GEN-LAST:event_IPKjFormattedActionPerformed

    private void ftftgllahirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftftgllahirFocusLost
        // TODO add your handling code here:
        try {
        String tanggalLahirText = ftftgllahir.getText().trim();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate tanggalLahir = LocalDate.parse(tanggalLahirText, formatter);

        LocalDate sekarang = LocalDate.now();
        int umur = Period.between(tanggalLahir, sekarang).getYears();

        if (umur < 18) {
            JOptionPane.showMessageDialog(null, "Usia tidak memenuhi syarat. Minimal 18 tahun.");
            ftftgllahir.requestFocus(); 
        }
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "Format tanggal tidak valid. Gunakan format yyyy-MM-dd.");
            ftftgllahir.requestFocus(); 
        }
    }//GEN-LAST:event_ftftgllahirFocusLost

    private void ftftgllahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftftgllahirActionPerformed
        // TODO add your handling code here:
        try {
        String tanggalLahirText = ftftgllahir.getText().trim();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate tanggalLahir = LocalDate.parse(tanggalLahirText, formatter);

        LocalDate sekarang = LocalDate.now();
        int umur = Period.between(tanggalLahir, sekarang).getYears();

        if (umur < 18) {
            JOptionPane.showMessageDialog(null, "Usia tidak memenuhi syarat. Minimal 18 tahun.");
            ftftgllahir.requestFocus(); 
        }
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(null, "Format tanggal tidak valid. Gunakan format yyyy-MM-dd.");
            ftftgllahir.requestFocus();
        }
    }//GEN-LAST:event_ftftgllahirActionPerformed

    private void IPKjFormattedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IPKjFormattedFocusLost
    String ipkString = IPKjFormatted.getText().trim();

    try {
        if (!ipkString.isEmpty()) {
            double ipk = Double.parseDouble(ipkString);

            if (ipk >= 0.00 && ipk <= 4.00) {
                System.out.println("IPK valid: " + ipk);
            } else {
                JOptionPane.showMessageDialog(this, "IPK tidak valid. Harus antara 0.00 dan 4.00.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                IPKjFormatted.setText("");
            }
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "IPK tidak valid. Masukkan angka dengan format yang benar.",
                "Error", JOptionPane.ERROR_MESSAGE);
        IPKjFormatted.setText("");
    }
    }//GEN-LAST:event_IPKjFormattedFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(biodataKuis2_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(biodataKuis2_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(biodataKuis2_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(biodataKuis2_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new biodataKuis2_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DaftarButton;
    private javax.swing.JFormattedTextField IPKjFormatted;
    private javax.swing.JTextField TelpText;
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.ButtonGroup btnGroupJk;
    private javax.swing.JCheckBox fotografiCheckBox;
    private javax.swing.JFormattedTextField ftftgllahir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JCheckBox membacaCheckBox;
    private javax.swing.JCheckBox menulisCheckBox;
    private javax.swing.JTextField namaText;
    private javax.swing.JTextField nikText1;
    private javax.swing.JComboBox<String> pendidikanComboBox;
    private javax.swing.JRadioButton perempuanRadioButton;
    // End of variables declaration//GEN-END:variables
}
